pipeline {
    agent any

    environment {
        ANSIBLE_VAULT_PASSWORD = credentials('ansible-vault-password')
    }

    stages {
        stage('Validate') {
            steps {
                script {
                    // Perform syntax check on the Ansible playbook
                    sh 'ansible-playbook --syntax-check manage-users.yml'
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    // Execute the Ansible playbook to manage user accounts
                    sh '''
                        ansible-playbook -i inventory.yml manage-users.yml \
                        --extra-vars "@users.yml" \
                        --vault-password-file <(echo $ANSIBLE_VAULT_PASSWORD)
                    '''
                }
            }
        }
    }
    post {
        always {
            // Archive the results, logs, and any other important files
            archiveArtifacts artifacts: '**/logs/*.log', allowEmptyArchive: true
        }
    }
}
